/* Auto-generated by scripts/extract-endproduct-wip-assets.mjs --emit-react */
import type { ImgHTMLAttributes } from 'react';

function wipUrl(name: string) {
  return `${import.meta.env.BASE_URL}wip-assets/svg/${name}`;
}

export function WipBoardAMainGameplay(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-main-gameplay.svg")} alt="" {...props} />;
}

export function WipBoardACardStates(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-card-states.svg")} alt="" {...props} />;
}

export function WipBoardAInteractions(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-interactions.svg")} alt="" {...props} />;
}

export function WipBoardATopBarDetails(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-top-bar-details.svg")} alt="" {...props} />;
}

export function WipBoardASidebarInGame(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-sidebar-in-game.svg")} alt="" {...props} />;
}

export function WipBoardAVisualTheme(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-visual-theme.svg")} alt="" {...props} />;
}

export function WipBoardAColorPalette(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-color-palette.svg")} alt="" {...props} />;
}

export function WipBoardATypography(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-a-typography.svg")} alt="" {...props} />;
}

export function WipBoardBMainMenu(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-b-main-menu.svg")} alt="" {...props} />;
}

export function WipBoardBSettings(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-b-settings.svg")} alt="" {...props} />;
}

export function WipBoardBModeSelection(props: ImgHTMLAttributes<HTMLImageElement>) {
  return <img src={wipUrl("board-b-mode-selection.svg")} alt="" {...props} />;
}


export const wipEndproductSvgFiles = {"board-a-main-gameplay":"board-a-main-gameplay.svg","board-a-card-states":"board-a-card-states.svg","board-a-interactions":"board-a-interactions.svg","board-a-top-bar-details":"board-a-top-bar-details.svg","board-a-sidebar-in-game":"board-a-sidebar-in-game.svg","board-a-visual-theme":"board-a-visual-theme.svg","board-a-color-palette":"board-a-color-palette.svg","board-a-typography":"board-a-typography.svg","board-b-main-menu":"board-b-main-menu.svg","board-b-settings":"board-b-settings.svg","board-b-mode-selection":"board-b-mode-selection.svg"} as const;
