/**
 * Glossary and simple blueprint v1 -> TypeScript in src/shared/generated/
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const defaultDefinitionsGlob = 'src/blueprint/definitions/**/*.blueprint.json';

/**
 * @param {{ repoRoot: string, definitionsDir?: string }} o
 * @returns {{ outFile: string, count: number, entryKeys: string[] }}
 */
export function runBlueprintCodegen(o) {
    const root = o.repoRoot;
    const defDir = o.definitionsDir
        ? path.join(root, o.definitionsDir)
        : path.join(root, 'src/blueprint/definitions');
    const files = listBlueprintJson(defDir);
    if (files.length === 0) {
        const out = path.join(root, 'src/shared/generated/blueprintGlossaryGen.ts');
        const stub = `// @generated by scripts/blueprint-codegen.mjs — do not edit
export const BLUEPRINT_GLOSSARY: Record<string, { en: string }> = {};
`;
        fs.mkdirSync(path.dirname(out), { recursive: true });
        fs.writeFileSync(out, stub, 'utf8');
        return { outFile: out, count: 0, entryKeys: [] };
    }
    const merged = {};
    const keys = [];
    for (const f of files.sort()) {
        const doc = JSON.parse(fs.readFileSync(f, 'utf8'));
        if (doc.blueprintVersion !== 1) {
            throw new Error(`Unsupported blueprint version in ${f}: ${doc.blueprintVersion}`);
        }
        if (doc.kind === 'glossary' && doc.entries) {
            for (const [k, v] of Object.entries(doc.entries)) {
                if (typeof (v).en === 'string') {
                    merged[k] = { en: (v).en };
                    keys.push(k);
                }
            }
        }
    }
    const outFile = path.join(root, 'src/shared/generated/blueprintGlossaryGen.ts');
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    const body = Object.entries(merged)
        .map(([k, v]) => {
            const key = JSON.stringify(k);
            const en = JSON.stringify((v).en);
            return `    ${key}: { en: ${en} }`;
        })
        .join(',\n');
    const header = `// @generated by scripts/blueprint-codegen.mjs — do not edit

`;
    const out = `${header}export const BLUEPRINT_GLOSSARY: Record<string, { en: string }> = {
${body}
} as const;
`;
    fs.writeFileSync(outFile, out, 'utf8');
    return { outFile, count: keys.length, entryKeys: keys };
}

/**
 * @param {string} dir
 * @returns {string[]}
 */
function listBlueprintJson(dir) {
    if (!fs.existsSync(dir)) {
        return [];
    }
    const out = [];
    const walk = (d) => {
        for (const name of fs.readdirSync(d, { withFileTypes: true })) {
            const p = path.join(d, name.name);
            if (name.isDirectory()) {
                walk(p);
            } else if (name.name.endsWith('.blueprint.json')) {
                out.push(p);
            }
        }
    };
    walk(dir);
    return out;
}

const main = () => {
    const root = path.resolve(__dirname, '..');
    const r = runBlueprintCodegen({ repoRoot: root });
    process.stdout.write(
        `Wrote ${r.outFile} (${r.count} keys): ${r.entryKeys.join(', ') || '(empty)'}\n`
    );
};

const thisFile = fileURLToPath(import.meta.url);
if (path.normalize(thisFile) === path.normalize(path.resolve(process.argv[1] ?? ''))) {
    main();
}
